version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 9453:9453
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
